[package]
name = "nipah_tokenizer"
version = "0.1.0"
edition = "2021"
authors = ["nipah~☆!"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bencher = "0.1.5"
lazy_static = "1.4.0"
